### ISSUE TITLE
Clicking on urls opens a new tab

### ISSUE THREAD

**Issue by dapetcu21** [chemzqm/stack-source-map#59]
Hi!

First of all, this is awesome! I really needed this in my life!

Yet, when clicking on the URLs in the error, the browser just opens a new tab with a blank page. Maybe it's because they should be `webpack://./src/index.js`? (with the dot in the middle)? Am I doing something wrong?

![screen shot 2017-03-17 at 11 49 16](https://cloud.githubusercontent.com/assets/428060/24037848/c7459a6c-0b07-11e7-8e3e-eeace673f4aa.png)

![screen shot 2017-03-17 at 11 51 08](https://cloud.githubusercontent.com/assets/428060/24037897/09bd06f0-0b08-11e7-910f-de2c7155708e.png)

**Comment by chemzqm** [comment]
It's because webpack generated wrong url, just an extra '/'.
I think you need `devtoolModuleFilenameTemplate` opition for webpack@2,  something like
``` js
  output: {
    path: path.join(__dirname, 'build'),
    filename: '[name].bundle.js',
    publicPath: '/build/',
    devtoolModuleFilenameTemplate: 'webpack://[absolute-resource-path]'
  }
```
should helps.
